### ISSUE TITLE
Julbock on fire

### ISSUE THREAD

**Issue by henryri** [marcus-e-e/bock-down-app#1]
The Julbock should burn if we had a winner.
So please add this fancy gif if the julbock is burned down: 
https://gph.is/2PYjV5t

![julbock-fire](https://user-images.githubusercontent.com/5763740/49152927-84efbe80-f314-11e8-9b7e-9a57bdeb3fab.gif)

**Comment by henryri** [comment]
Here a link to the dark mode (fire is more cozy in the dark)
https://giphy.com/gifs/fire-sweden-julbock-8TtK6I7VvfgRrmeXdy

![julbock-fire-dark](https://user-images.githubusercontent.com/5763740/49153829-1eb86b00-f317-11e8-85a8-17fee05cba9c.gif)

**Comment by marcus-e-e** [comment]
Fancy gif will be added wit the next version. Dark mode is not on the roadmap at the moment. Sorry.
