### ISSUE TITLE
Add Twitter Stream from Gävlebocken

### ISSUE THREAD

**Issue by henryri** [marcus-e-e/bock-down-app#2]
Please add the official twitter stream of the Gävlebocken.
https://twitter.com/Gavlebocken 

See https://www.npmjs.com/package/react-twitter-embed for futher informations

**Comment by henryri** [comment]
Twitter is great but feel free to add Instagram as alternative

**Comment by marcus-e-e** [comment]
Did not find a library for Instagram and I think it will clutter the design. Added links to both social sites.
