### ISSUE TITLE
Remove spacing

### ISSUE THREAD

**Issue by henryri** [marcus-e-e/bock-down-app#4]
https://github.com/marcus-e-e/bock-down-app/blob/e5372abcc9779d1c72065f352607d24c1701d192/src/pages/index.js#L88 please remove this line. 

The site looks like it has a fat reserve for the winter ⛄️. Please bring the site to the next gym 🏋️

**Comment by marcus-e-e** [comment]
Done. Site slimed down to fit the screen.
